# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kiO5jOIr9MP9sd4aRzw6cKT72pEjnRvm
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.optimize import differential_evolution, minimize

# 1. Load Data
df = pd.read_csv("xy_data.csv")
x_data = df["x"].values
y_data = df["y"].values

# 2. Objective Function using L1 Distance
def l1_loss(params):
    theta_deg, M, X = params
    rad = np.radians(theta_deg)
    cos_rad = np.cos(rad)
    sin_rad = np.sin(rad)

    # Analytical substitution to calculate t directly for each point
    t = (x_data - X) * cos_rad + (y_data - 42) * sin_rad

    # Model equations
    x_pred = (
        t * cos_rad - np.exp(M * np.abs(t)) * np.sin(0.3 * t) * sin_rad + X
    )
    y_pred = (
        42 + t * sin_rad + np.exp(M * np.abs(t)) * np.sin(0.3 * t) * cos_rad
    )

    # Compute L1 Loss
    return np.sum(np.abs(x_pred - x_data) + np.abs(y_pred - y_data))

# 3. Global Optimization via Differential Evolution
bounds = [(0.0, 50.0), (-0.05, 0.05), (0.0, 100.0)]
res_de = differential_evolution(l1_loss, bounds, seed=42, tol=1e-12)

# 4. Local Refinement using L-BFGS-B
res_fine = minimize(
    l1_loss, res_de.x, method="L-BFGS-B", bounds=bounds, tol=1e-15
)

theta_opt, M_opt, X_opt = res_fine.x
rad_opt = np.radians(theta_opt)

print("=== OPTIMIZATION RESULTS ===")
print(f"Theta (degrees): {theta_opt:.4f}°")
print(f"Theta (radians): {rad_opt:.10f} rad")
print(f"M:               {M_opt:.4f}")
print(f"X:               {X_opt:.4f}")
print(f"L1 Distance:     {res_fine.fun:.6f}")

# 5. Generate and Save Plot
t_samples = np.linspace(6, 60, 1000)
x_curve = (
    t_samples * np.cos(rad_opt)
    - np.exp(M_opt * t_samples) * np.sin(0.3 * t_samples) * np.sin(rad_opt)
    + X_opt
)
y_curve = (
    42.0
    + t_samples * np.sin(rad_opt)
    + np.exp(M_opt * t_samples) * np.sin(0.3 * t_samples) * np.cos(rad_opt)
)

plt.figure(figsize=(10, 6))
plt.scatter(
    x_data, y_data, color="blue", alpha=0.5, s=15, label="Given xy_data.csv"
)
plt.plot(
    x_curve,
    y_curve,
    color="red",
    linewidth=2,
    label=r"Fitted Curve ($\theta=30^\circ, M=0.03, X=55$)",
)
plt.xlabel("x")
plt.ylabel("y")
plt.title("Parametric Curve Optimization & Line Fit")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.tight_layout()
plt.savefig("curve_fit_result.png", dpi=300)
print("Plot successfully saved as curve_fit_result.png")
